### ISSUE TITLE
Qcluster implementieren um Notifications in einer Queue zu speichern und zu senden

### ISSUE THREAD

**Issue by Grayknife** [random-rip/primebot_backend#8]
Qcluster implementieren um Notifications in einer Queue zu speichern und zu senden. 

Der große Vorteil, Fehler von Discord und Telegram
- 502 Bad Gateway, Discord
- Parse URLLibException, Telegram
- 429 telepot.exception.TooManyRequestsError, Telegram
- telepot.exception.TelegramError: ('Bad Gateway', 502, {'ok': False, 'error_code': 502, 'description': 'Bad Gateway'})
- NoneType
```
[17/Jun/2022 13:53:12] ERROR [notifications:93]
NoneType: None
```

können abgefangen und nach kurzer Zeit nochmal zugestellt werden.

#### Errormessages:

```
[12/Jun/2022 03:11:31] ERROR [notifications:27] Error Sending Message in Chat chat_id=XXX msg=Ein gravierender Fehler ist aufgetreten.
Bad Gateway
('Bad Gateway', 502, {'ok': False, 'error_code': 502, 'description': 'Bad Gateway'})
Traceback (most recent call last):
  File "/opt/prime_bot/prime_bot_backend/bots/telegram_interface/telegram_bot.py", line 94, in error
    context.bot.send_message(settings.TG_DEVELOPER_GROUP, text, parse_mode=ParseMode.HTML)
  File "/opt/prime_bot/prime_bot_backend/venv/lib/python3.8/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/opt/prime_bot/prime_bot_backend/venv/lib/python3.8/site-packages/telegram/bot.py", line 67, in decorator
    result = func(*args, **kwargs)
  File "/opt/prime_bot/prime_bot_backend/venv/lib/python3.8/site-packages/telegram/bot.py", line 346, in send_message
    return self._message(url, data, disable_notification=disable_notification,
  File "/opt/prime_bot/prime_bot_backend/venv/lib/python3.8/site-packages/telegram/bot.py", line 175, in _message
    result = self._request.post(url, data, timeout=timeout)
  File "/opt/prime_bot/prime_bot_backend/venv/lib/python3.8/site-packages/telegram/utils/request.py", line 330, in post
    result = self._request_wrapper('POST', url,
  File "/opt/prime_bot/prime_bot_backend/venv/lib/python3.8/site-packages/telegram/utils/request.py", line 254, in _request_wrapper
    raise NetworkError('Bad Gateway')
telegram.error.NetworkError: Bad Gateway

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/prime_bot/prime_bot_backend/bots/telegram_interface/tg_singleton.py", line 25, in send_message
    return bot.sendMessage(chat_id=chat_id, text=msg, parse_mode=parse_mode, disable_web_page_preview=True)
  File "/opt/prime_bot/prime_bot_backend/venv/lib/python3.8/site-packages/telepot/__init__.py", line 513, in sendMessage
    return self._api_request('sendMessage', _rectify(p))
  File "/opt/prime_bot/prime_bot_backend/venv/lib/python3.8/site-packages/telepot/__init__.py", line 491, in _api_request
    return api.request((self._token, method, params, files), **kwargs)
  File "/opt/prime_bot/prime_bot_backend/venv/lib/python3.8/site-packages/telepot/api.py", line 155, in request
    return _parse(r)
  File "/opt/prime_bot/prime_bot_backend/venv/lib/python3.8/site-packages/telepot/api.py", line 150, in _parse
    raise exception.TelegramError(description, error_code, data)
telepot.exception.TelegramError: ('Bad Gateway', 502, {'ok': False, 'error_code': 502, 'description': 'Bad Gateway'})
```

```
[06/Jun/2022 12:32:57] ERROR [notifications:27] Error Sending Message in Chat chat_id=XXX msg=DISCORD
user: 9a444572d64d92bd269f
command: !start https://www.primeleague.gg/leagues/teams/182095-black-lion-lethal-tempo
server: Test
members: 3
('Too Many Requests: retry after 39', 429, {'ok': False, 'error_code': 429, 'description': 'Too Many Requests: retry after 39', 'parameters': {'retry_after': 39}})
Traceback (most recent call last):
  File "/opt/prime_bot/prime_bot_backend/bots/telegram_interface/tg_singleton.py", line 25, in send_message
    return bot.sendMessage(chat_id=chat_id, text=msg, parse_mode=parse_mode, disable_web_page_preview=True)
  File "/opt/prime_bot/prime_bot_backend/venv/lib/python3.8/site-packages/telepot/__init__.py", line 513, in sendMessage
    return self._api_request('sendMessage', _rectify(p))
  File "/opt/prime_bot/prime_bot_backend/venv/lib/python3.8/site-packages/telepot/__init__.py", line 491, in _api_request
    return api.request((self._token, method, params, files), **kwargs)
  File "/opt/prime_bot/prime_bot_backend/venv/lib/python3.8/site-packages/telepot/api.py", line 155, in request
    return _parse(r)
  File "/opt/prime_bot/prime_bot_backend/venv/lib/python3.8/site-packages/telepot/api.py", line 147, in _parse
    raise e(description, error_code, data)
telepot.exception.TooManyRequestsError: ('Too Many Requests: retry after 39', 429, {'ok': False, 'error_code': 429, 'description': 'Too Many Requests: retry after 39', 'parameters': {'retry_after': 39}})
```

**Comment by Grayknife** [comment]
```
[10/Jul/2022 20:14:46] ERROR [notifications:96]   File "/opt/prime_bot/prime_bot_backend/venv/lib/python3.8/site-packages/telegram/ext/dispatcher.py", line 340, in process_update
    handler.handle_update(update, self, check, context)
  File "/opt/prime_bot/prime_bot_backend/venv/lib/python3.8/site-packages/telegram/ext/conversationhandler.py", line 465, in handle_update
    new_state = handler.handle_update(update, dispatcher, check_result, context)
  File "/opt/prime_bot/prime_bot_backend/venv/lib/python3.8/site-packages/telegram/ext/handler.py", line 119, in handle_update
    return self.callback(update, context)
  File "/opt/prime_bot/prime_bot_backend/utils/messages_logger.py", line 38, in wrapper
    result = fn(*args, **kwargs)
  File "/opt/prime_bot/prime_bot_backend/bots/telegram_interface/commands/single_commands.py", line 99, in helpcommand
    update.message.reply_markdown(
  File "/opt/prime_bot/prime_bot_backend/venv/lib/python3.8/site-packages/telegram/message.py", line 539, in reply_markdown
    return self.bot.send_message(self.chat_id, *args, **kwargs)
  File "/opt/prime_bot/prime_bot_backend/venv/lib/python3.8/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/opt/prime_bot/prime_bot_backend/venv/lib/python3.8/site-packages/telegram/bot.py", line 67, in decorator
    result = func(*args, **kwargs)
  File "/opt/prime_bot/prime_bot_backend/venv/lib/python3.8/site-packages/telegram/bot.py", line 346, in send_message
    return self._message(url, data, disable_notification=disable_notification,
  File "/opt/prime_bot/prime_bot_backend/venv/lib/python3.8/site-packages/telegram/bot.py", line 175, in _message
    result = self._request.post(url, data, timeout=timeout)
  File "/opt/prime_bot/prime_bot_backend/venv/lib/python3.8/site-packages/telegram/utils/request.py", line 330, in post
    result = self._request_wrapper('POST', url,
  File "/opt/prime_bot/prime_bot_backend/venv/lib/python3.8/site-packages/telegram/utils/request.py", line 244, in _request_wrapper
    raise BadRequest(message)
Traceback (most recent call last):
  File "/opt/prime_bot/prime_bot_backend/venv/lib/python3.8/site-packages/telegram/ext/dispatcher.py", line 340, in process_update
    handler.handle_update(update, self, check, context)
  File "/opt/prime_bot/prime_bot_backend/venv/lib/python3.8/site-packages/telegram/ext/conversationhandler.py", line 465, in handle_update
    new_state = handler.handle_update(update, dispatcher, check_result, context)
  File "/opt/prime_bot/prime_bot_backend/venv/lib/python3.8/site-packages/telegram/ext/handler.py", line 119, in handle_update
    return self.callback(update, context)
  File "/opt/prime_bot/prime_bot_backend/utils/messages_logger.py", line 38, in wrapper
    result = fn(*args, **kwargs)
  File "/opt/prime_bot/prime_bot_backend/bots/telegram_interface/commands/single_commands.py", line 99, in helpcommand
    update.message.reply_markdown(
  File "/opt/prime_bot/prime_bot_backend/venv/lib/python3.8/site-packages/telegram/message.py", line 539, in reply_markdown
    return self.bot.send_message(self.chat_id, *args, **kwargs)
  File "/opt/prime_bot/prime_bot_backend/venv/lib/python3.8/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/opt/prime_bot/prime_bot_backend/venv/lib/python3.8/site-packages/telegram/bot.py", line 67, in decorator
    result = func(*args, **kwargs)
  File "/opt/prime_bot/prime_bot_backend/venv/lib/python3.8/site-packages/telegram/bot.py", line 346, in send_message
    return self._message(url, data, disable_notification=disable_notification,
  File "/opt/prime_bot/prime_bot_backend/venv/lib/python3.8/site-packages/telegram/bot.py", line 175, in _message
    result = self._request.post(url, data, timeout=timeout)
  File "/opt/prime_bot/prime_bot_backend/venv/lib/python3.8/site-packages/telegram/utils/request.py", line 330, in post
    result = self._request_wrapper('POST', url,
  File "/opt/prime_bot/prime_bot_backend/venv/lib/python3.8/site-packages/telegram/utils/request.py", line 244, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Can't parse entities: can't find end of the entity starting at byte offset 292
```
